### ISSUE TITLE
app crash with certain expressions

### ISSUE THREAD

**Issue by r1cola** [EmreTech/Calculator_NX#11]
app will soft crash (close with an HOS message) upon performing the following:

- enter only an operator symbol - like "/" or "^"
- press "="

only tested 2.0.1 Stable NRO version via non-applet mode

**Comment by EmmmaTech** [comment]
I can't reproduce this problem. For `+`, `-`, and `*` I just get 0 but for `/` I get nan (because of 0 / 0)

**Comment by EmmmaTech** [comment]
Closing since I cannot reproduce.
