### ISSUE TITLE
Directory rename from "kr-KO" to "ko"

### ISSUE THREAD

**Issue by DDinghoya** [EmreTech/Calculator_NX#16]
When I thought about it, Directory name is wrong by HOS localizations.

<img width="369" alt="locale" src="https://user-images.githubusercontent.com/19677686/206862087-a91190b2-accc-45c7-a863-43733338d34a.png">

Can you change it to "ko"?

Or should I delete the directory and create a new one?

**Comment by EmmmaTech** [comment]
I'll rename it, thanks for pointing that out!

**Comment by EmmmaTech** [comment]
Resolved in 21eadc940903df5adf7b3e014af006fd1ebbcb42.
